<?php

namespace Database\Seeders;

use App\Models\HospitalDepartment;
use App\Models\HospitalService;
use App\Models\User;
use Illuminate\Database\Seeder;

class HospitalServicesSeeder extends Seeder
{
    public function run()
    {
        try {
            $services = [
                [
                    'name' => 'Dịch vụ tẩy trắng răng',
                    'infor' => json_encode([
                        'about_service' => '<p><p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline">Tẩy trắng răng là kỹ thuật nha khoa thẩm mỹ phổ biến giúp cải thiện các vấn đề liên quan đến độ trắng sáng, đều màu của răng.<br /><br />Phương pháp được áp dụng dành cho trường hợp khách hàng gặp các vấn đề như răng bị xỉn màu bởi các chất kích thích như rượu bia, thuốc lá, răng ố vàng do vệ sinh không hiệu quả hoặc do nhiễm trùng màu kháng sinh mức độ 1 và 2.</span></p><p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline"><br />Phòng khám Đa khoa Quốc tế Sài Gòn hiện đang triển khai gói dịch vụ Tẩy trắng răng nội tủy (1 răng), tẩy trắng răng tại chỗ 1 hàm, tẩy trắng răng tại chỗ bằng đèn Zoom 2. Bên cạnh đó, với hệ thống trang thiết bị hiện đại, quy trình tẩy trắng răng rành mạch, quý khách hàng cũng có thể chọn lựa hình thức tẩy trắng răng tại nhà hoặc tẩy trắng răng tại phòng khám.</span></p><br /></p>',
                        'prepare_process' => '<p></p>
                            <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Khách hàng có thể trao đổi với các y bác sĩ về tình trạng bệnh lý răng miệng đã và đang mắc phải (nếu có) trước khi tiến hành tẩy trắng răng.</span>
                            <br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" />
                            <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Một số trường hợp như phụ nữ có thai, đang cho con bú, hoặc những người có cấu trúc của thân răng không tốt, tuyệt đối không nên làm trắng răng, vì chắc chắn sẽ ảnh hưởng tới nướu, tụt lợi hoặc nứt răng gây ê buốt và kích thích tủy. Nên đến các nha khoa uy tín để được các bác sĩ xem xét, chỉ định có nên làm trắng răng hay không.</span>
                            <br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" />
                            <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Không nên sử dụng ngay lập tức những đồ uống như trà, cà phê, thực phẩm có phẩm màu sau khi vừa tiến hành tẩy trắng răng.&nbsp;</span>',
                        'service_details' => '<p></p>
                            <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; white-space: pre-line">Dịch vụ Tẩy trắng răng tại phòng khám Đa khoa Quốc tế Sài Gòn bao gồm các hạng mục như:
                            • Tẩy trắng răng nội tuỷ (1 răng)
                            • Tẩy trắng tại chỗ 1 hàm
                            • Tẩy trắng tại chổ bằng đèn Zoom 2
                            • Tẩy trắng tại nhà
                            • Tẩy trắng tại phòng khám loại 2</span>',
                        'location' => [19, 29],
                    ]),
                ],
                [
                    'name' => 'Trám răng kẽ hở 2 răng',
                    'infor' => json_encode([
                        'about_service' => '<p></p>
                            <p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline">Trám răng thưa là phương pháp sử dụng các vật liệu trám nhằm thu hẹp các kẽ hở của răng một cách tự nhiên.<br /><br />Phòng khám Đa khoa Quốc tế Sài Gòn hiện đang triển khai gói dịch vụ Trám răng kẽ hở 2 răng nhằm cải thiện các vấn đề liên quan đến tính thẩm mỹ, đảm bảo chức năng ăn nhai của răng.</span></p>
                            <p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline"><br />Quy trình trám răng thưa diễn ra tương đối nhanh chóng và tiết kiệm chi phí. Khoảng hở được lấp đầy nhờ răng 2 bên được trám rộng ra, nhưng vẫn được tách biệt bởi một khe hẹp ở giữa một cách tự nhiên.</span></p>',
                        'prepare_process' => '<p>
                            </p>
                            <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Quá trình trám răng diễn ra tương đối nhanh chóng và đơn giản, không gây cảm giác đau đớn, vì thế bạn hoàn toàn có thể thoải mái trước khi tiến hành trám răng.</span>
                            <br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" />
                            <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Không nên ăn ngay sau khi tiến hành trám. Có thể ăn sau khoảng từ 1 - 2 giờ nhằm giúp cho vật liệu trám đông cứng hoàn toàn và đảm bảo hiệu quả chỗ trám.</span>',
                        'service_details' => '<p></p>
                            <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; white-space: pre-line">Quy trình trám răng:
                            • Bác sĩ tiến hành thăm khám và tư vấn
                            • Gây tê và vệ sinh chỗ cần trám
                            • Tiến hành trám
                            • Kiểm tra, chỉnh sửa chỗ trám và hoàn tất</span>',
                        'location' => [19, 29],
                    ]),
                ],
                [
                    'name' => 'Cạo vôi răng',
                    'infor' => json_encode([
                        'about_service' => '<p>

                        <p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline">Cao răng hay vôi răng là những mảng bám thức ăn trên kẽ răng đã bị vôi hóa. Cạo vôi răng là phương pháp nha khoa giúp làm sạch, vệ sinh răng miệng, loại bỏ các mảng cao răng hình thành trên răng.<br /><br />Tình trạng cao răng lâu ngày không lấy có thể gây ảnh hưởng đến tính thẩm mỹ, tăng nguy cơ hôi miệng, ê buốt, sâu răng và các vấn đề bệnh lý như viêm nướu, nghiêm trọng hơn là viêm nha chu.</span></p><p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline"><br />Phòng khám Đa khoa Quốc tế Sài Gòn hiện đang triển khai gói dịch vụ lấy cao răng chia theo từng cấp độ 1, cấp độ 2 và cấp độ 3. Dịch vụ được tiến hành thực hiện bởi đội ngũ y bác sĩ dày dặn kinh nghiệm, cùng hệ thống trang thiết bị hiện đại tại phòng khám.</span></p>
                        <br /></p>',
                        'prepare_process' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Trẻ em dưới 10 tuổi không nên lấy cao răng vì lúc này răng vẫn chưa hoàn thiện, gây ảnh hưởng đến các răng mới mọc.</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Thai phụ không nên tiến hành lấy cao răng ở giai đoạn đầu và giai đoạn cuối của thai kỳ để đảm bảo sức khỏe thai nhi</span>
                        <br /></p>',
                        'service_details' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; white-space: pre-line">Phòng khám hiện đang triển khai các hạng mục dịch vụ lấy cao răng:
                        • Lấy cao răng cấp 1: 500,000 VNĐ
                        • Lấy cao răng cấp 2: 400,000 VNĐ
                        • Lấy cao răng cấp 3: 300,000 VNĐ
                        • Lấy cao răng trẻ em: 250,000 VNĐ</span>
                        <br /></p>',
                        'location' => [19, 29],
                    ]),
                ],
                [
                    'name' => 'Nhổ răng khôn',
                    'infor' => json_encode([
                        'about_service' => '<p>

                        <p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline">Răng khôn là răng mọc cuối cùng và thường xuất hiện ở độ tuổi từ 17 đến 25. Việc răng khôn xuất hiện và phải tiến hành nhổ bỏ vẫn luôn khiến nhiều người nghi ngại bởi mức độ đau và nguy cơ biến chứng.<br /><br />Với lợi thế sở hữu trang thiết bị hiện đại cùng đội ngũ y bác sĩ chuyên khoa dày dặn kinh nghiệm, phòng khám Đa khoa Quốc tế Sài Gòn hiện đang triển khai các hạng mục nhổ răng khôn vĩnh viễn với những nhóm răng: nhóm răng khôn lệch, nhóm răng khôn ngầm, nhóm răng khôn thẳng,...</span></p><p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline"><br />Quá trình được thực hiện nghiêm ngặt, giảm bớt tối đa cảm giác đau, kiểm soát biến chứng và hỗ trợ khách hàng trong việc hồi phục sau quá trình nhổ răng khôn.</span></p>
                        <br /></p>',
                        'prepare_process' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">Trước khi tiến hành nhổ răng khôn, khách hàng cần lưu ý:</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Vệ sinh răng miệng sạch sẽ</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Lấy sạch cao răng, mảng bám trên răng</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Không uống rượu bia trước khi nhổ răng một ngày</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Nắm rõ tiền sử bệnh của bản thân, các loại thuốc đang sử dụng để trao đổi cùng các bác sĩ</span>
                        <br /></p>',
                        'service_details' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; white-space: pre-line">Phòng khám Đa khoa Quốc tế Sài Gòn hiện đang triển khai các loại hình nhổ răng khôn như:
                        • Nhổ răng khôn vĩnh viễn nhóm răng khôn lệch
                        • Nhổ răng khôn vĩnh viễn nhóm răng khôn ngầm
                        • Nhổ răng khôn vĩnh viễn nhóm răng khôn thẳng</span>
                        <br /></p>',
                        'location' => [19, 29],
                    ]),
                ],
                [
                    'name' => 'Nội soi đại tràng',
                    'infor' => json_encode([
                        'about_service' => '<p>

                        <p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline">Nội soi đại tràng là thủ thuật nhằm mục đích hỗ trợ các y bác sĩ quan sát toàn bộ chiều dài của đại tràng và trực tràng, tầm soát các bất thường trong ruột cũng như khối u thịt nhỏ nằm trên thành đại tràng.<br /><br />Bệnh nhân có thể tiến hành nội soi đại tràng nhằm mục đích tìm kiếm nguyên nhân các dấu hiệu và triệu chứng đường ruột, tầm soát ung thư đại tràng, xem xét bệnh nhân có polyp đại tràng hay không.</span></p><p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline"><br />Quá trình nội soi đại tràng thường mất khoảng từ 30 - 45 phút. Các bác sĩ sẽ đưa một ống nhựa dẻo có gắn camera và đèn vào hậu môn, quan sát các cấu trúc bên trong ruột cũng như tìm kiếm các tổn thương như viêm hoặc polyp.</span></p>
                        <br /></p>',
                        'prepare_process' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Bạn không nên ăn thức ăn cứng khô trước khi tiến hành nội soi.</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Bác sĩ có thể đề nghị uống thuốc nhuận tràng dưới dạng thuốc viên hoặc dạng lỏng.</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Trong một số trường hợp, bạn có thể cần phải sử dụng bộ bơm trực tràng (hay còn gọi là thụt tháo đại tràng) để làm sạch đại tràng vào đêm trước hoặc vài tiếng trước khi khám.</span>
                        <br /></p>',
                        'service_details' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; white-space: pre-line">• Quá trình nội soi đại tràng thường mất khoảng từ 30 - 45 phút. Các bác sĩ sẽ tiến hành đưa thiết bị nội soi vào hậu môn, bơm không khí vào ruột già làm cho đoạn ruột phồng ra nhờ vậy có thể quan sát các cấu trúc bên trong ruột một cách rõ hơn.</span>
                        <br /></p>',
                        'location' => [19, 29],
                    ]),
                ],
                [
                    'name' => 'Nội soi dạ dày',
                    'infor' => json_encode([
                        'about_service' => '<p>

                        <p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline">Nội soi dạ dày là kỹ thuật nhằm mục đích hỗ trợ các y bác sĩ có thể quan sát các cơ quan của ống tiêu hóa (thực quản, dạ dày, tá tràng) nhằm phục vụ cho quá trình chẩn đoán và điều trị bệnh.<br /><br />Quá trình nội soi được thực hiện khi các y bác sĩ sẽ tiến hành dùng ống nội soi chuyên dụng có gắn camera đi qua cổ họng, xuống dạ dày để xem xét, đánh giá các tổn thương bên trong thông qua hình ảnh trên màn hình máy tính.</span></p><p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline"><br />Bệnh nhân có thể được chỉ định nội soi nhằm mục đích tầm soát các triệu chứng bất thường như: chảy máu bất thường, khó nuốt, đau bụng, nghi ngờ mắc các vấn đề bệnh lý liên quan đến dạ dày,...</span></p>
                        <br /></p>',
                        'prepare_process' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Trước khi tiến hành nội soi dạ dày, bệnh nhân cần nhịn ăn trước khi tiến hành thủ thuật khoảng 6 giờ. Tuy nhiên, bạn có thể uống một ít nước trước đó khoảng 2 giờ.</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Nếu bệnh nhân đang trong quá trình sử dụng các loại thuốc làm loãng máu, hãy thông báo cho bác sĩ khi tiến hành thực hiện thủ thuậ</span>
                        <br /></p>',
                        'service_details' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; white-space: pre-line">"• Quá trình nội soi dạ dày kéo dài khoảng 15 phút. Thông thường, bệnh nhân sẽ được tiến hành nội soi trong trạng thái tỉnh táo. Nếu cần thiết bạn sẽ được sử dụng thuốc gây mê để khi thực hiện thủ thuật.
                        
                        • Bệnh nhân sẽ được hướng dẫn tư thế nằm phù hợp, các bác sĩ tiến hành đưa thiết bị nội soi vào miệng, xuống cổ họng và đến thực quản, tầm soát các vấn đề bất thường thông qua hình ảnh trên màn hình. "</span>
                        <br /></p>',
                        'location' => [19, 29],
                    ]),
                ],
                [
                    'name' => 'Soi cổ tử cung',
                    'infor' => json_encode([
                        'about_service' => '<p>

                        <p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline">Soi cổ tử cung là thủ thuật được sử dụng nhằm hỗ trợ các y bác sĩ trong việc quan sát âm hộ, âm đạo và cổ tử cung, sàng lọc các vấn đề bệnh lý phụ khoa cũng như các tổn thương nghi ngờ ung thư cổ tử cung.<br /><br />Quá trình soi cổ tử cung được thực hiện khi các bác sĩ sẽ dùng thiết bị soi chuyên dụng để đưa vào bên trong âm đạo. Thiết bị hỗ trợ ghi lại các hình ảnh niêm mạc âm đạo và cổ tử cung nhằm ghi lại những vùng bất thường nổi rõ lên so với những vùng bình thường còn lại.</span></p><p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline"><br />Bệnh nhân có thể được chỉ định thực hiện soi cổ tử cung khi phát hiện các bất thường trong quá trình khám âm đạo nhằm mục đích: tầm soát mụn cóc sinh dục hay HPV, viêm nhiễm cổ tử cung, sự phát triển bất thường ở cổ tử cung hay niêm mạc âm đạo.</span></p>
                        <br /></p>',
                        'prepare_process' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">Để việc soi cổ tử cung mang lại kết quả chính xác, quý khách cần lưu ý một số điều sau trước khi soi cổ tử cung:</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Không nên soi tử cung trong thời gian đang có kinh nguyệt.</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Nên ngừng quan hệ tình dục ít nhất hai ngày trước khi soi cổ tử cung.</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Không sử dụng thuốc giảm đau.</span><br style=" color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px" /><span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Không nên sử dụng băng vệ sinh trong vòng 2 ngày trước khi soi cổ tử cung.</span>
                        <br /></p>',
                        'service_details' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; white-space: pre-line">Quy trình thực hiện soi cổ tử cung tại phòng khám:
                        
                        • Bệnh nhân được hướng dẫn nằm ngửa, hai chân kê cao.
                        • Bác sĩ dùng mỏ vịt để mở rộng âm đạo, cổ tử cung của bệnh nhân.
                        • Bác sĩ lau nhẹ chất tiết âm đạo che mờ vùng khảo sát bằng gạc hoặc tampon.
                        • Bác sĩ dùng máy soi đặt ở ngoài soi vào trong âm đạo để quan sát.
                        • Nếu phát hiện tổn thương hay có nghi ngờ, bác sĩ sẽ chỉ định sinh thiết.</span>
                        <br /></p>',
                        'location' => [19, 29],
                    ]),
                ],
                [
                    'name' => 'Đo loãng xương',
                    'infor' => json_encode([
                        'about_service' => '<p>

                        <p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline">Loãng xương là tình trạng suy giảm mật độ xương khiến xương trở nên yếu giòn và dễ gãy hơn. Phần lớn các trường hợp loãng xương đều không có biểu hiện lâm sàng cho đến khi xảy ra tình trạng gãy xương. Vì thế, đo loãng xương chính là biện pháp cần thiết nhằm dự đoán và giảm nguy cơ gãy xương trong tương lai.<br /><br />Quá trình đo loãng xương diễn ra tương đối nhanh chóng và đơn giản mất khoảng từ 20 - 30 phút. Sau khi tiến hành đo loãng xương, các y bác sĩ sẽ đọc kết quả, so sánh các thông số về mật độ xương.</span></p><p data-size="base" data-type="regular" class="wIj6fkD " style=" font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-variant-position: inherit; font-stretch: inherit; line-height: 24px; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; vertical-align: baseline; color: var(--custom-color,#262626)"><span style=" font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 16px; letter-spacing: inherit; vertical-align: baseline"><br />Bệnh nhân có thể tiến hành đo loãng xương trong trường hợp có kết quả chụp X-quang thấy có chỗ bị thiếu xương, gãy xương ở cột sống, hay bị đau lưng và nguy cơ gãy đốt sống. Ngoài ra, bất cứ khi nào cảm thấy bản thân gặp các vấn đề về xương khớp, nên tiến hành gặp các bác sĩ chuyên khoa để được thăm khám, đánh giá và có được phác đồ điều trị đúng đắn hiệu quả.</span></p>
                        <br /></p>',
                        'prepare_process' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px">• Bệnh nhân không nên đeo đồ trang sức kim loại hoặc mặc quần áo có các chi tiết kim loại khi tiến hành thực hiện đo loãng xương.</span>
                        <br /></p>',
                        'service_details' => '<p>

                        <span style="color: rgb(38, 38, 38); font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Helvetica Neue&quot;, sans-serif; font-size: 16px; white-space: pre-line">Bác sĩ sẽ hướng dẫn bệnh nhân nằm trên giường đệm của máy đo. Quá trình đo thường diễn ra trong khoảng 20 - 30 phút. Sau quá trình đo, các y bác sĩ sẽ tiến hành đọc kết quả, so sánh các thông số và tư vấn về biện pháp phòng ngừa cũng như điều trị cho bệnh nhân.</span>
                        <br /></p>',
                        'location' => [19, 29],
                    ]),
                ],
            ];

            $hospitals = User::where('role', 'hospital')->limit(3)->get();
            foreach ($hospitals as $index => $hospital) {
                $ids = HospitalDepartment::where('id_hospital', $hospital->id)->get()->pluck('id');
                foreach ($services as $index => $service) {
                    $data = array_merge(
                        $service,
                        [
                            'id_hospital_department' => $ids->random(),
                            'time_advise' => random_int(1, 4) * 30,
                            'price' => random_int(1, 60) * 50000,
                            'is_delete' => false,
                            'created_at' => now(),
                            'updated_at' => now(),
                        ]
                    );
                    HospitalService::create($data);
                }
            }
        } catch (\Exception $e) {
        }
    }
}
